### PR TITLE
Document internal structs

### PR DESCRIPTION
**Pull request by NagithaAbeywickrema**
C structs are documented as in [Doxygen tests](https://github.com/doxygen/doxygen/blob/69342febd375499da5510f9dd09e379ea415e7b7/testing/100_a.c#L57). But for some unfound reason, the members of the struct is not being parsed when the docs are built. The output is as followed,
image

### CODE REVIEW

**Comment by thilinarmtb** [comment]
Did you try doing what is here? https://scilab.gitlab.io/legacy_wiki/Doxygen(20)documentation(20)Examples

**Comment by NagithaAbeywickrema** [comment]
> Did you try doing what is here? https://scilab.gitlab.io/legacy_wiki/Doxygen(20)documentation(20)Examples

Yes, still the same result.

**Comment by thilinarmtb** [comment]
@NagithaAbeywickrema : This seem to be an issue with Sphinx and/or breathe. If you generate the Doxygen docs,
they contain the struct documentation.

**Comment by thilinarmtb** [comment]
With these changes, I can get the structs to appear on documentation:
https://github.com/thilinarmtb/doxygen-sphinx-breath-cmake/commit/28fc2e15e2c61456c1b54267dc42540568b84cc9

I created a dummy project to test this here:
https://github.com/thilinarmtb/doxygen-sphinx-breath-cmake

**Comment by NagithaAbeywickrema** [comment]
> With the following changes, I can get the structs to appear on documentation: [thilinarmtb/doxygen-sphinx-breath-cmake@28fc2e1](https://github.com/thilinarmtb/doxygen-sphinx-breath-cmake/commit/28fc2e15e2c61456c1b54267dc42540568b84cc9)
> 
> I created a dummy project to test this here: https://github.com/thilinarmtb/doxygen-sphinx-breath-cmake

I was able to generate docs for struct members by adding the `:members:` tag to the `nomp_types` group in `user-api.rst` file. Currently the issues are,
- `#include <nomp-impl.h>` is present before the description of all the structs in the `nomp-impl.h` file.
- Only the structs in the `nomp-impl.h` file are being documented

**Comment by thilinarmtb** [comment]
> > With the following changes, I can get the structs to appear on documentation: [thilinarmtb/doxygen-sphinx-breath-cmake@28fc2e1](https://github.com/thilinarmtb/doxygen-sphinx-breath-cmake/commit/28fc2e15e2c61456c1b54267dc42540568b84cc9)
> > I created a dummy project to test this here: https://github.com/thilinarmtb/doxygen-sphinx-breath-cmake
> 
> I was able to generate docs for struct members by adding the `:members:` tag to the `nomp_types` group in `user-api.rst` file. Currently the issues are,
> 
> * `#include <nomp-impl.h>` is present before the description of all the structs in the `nomp-impl.h` file.
>   image
> * Only the structs in the `nomp-impl.h` file are being documented.

Does it go away if we add each struct separately using `doxygenstruct` instead of `doxygengroup`?
Also, we need the internal structs to be documented in `internal-api.rst` not in `user-api.rst`.

**Comment by NagithaAbeywickrema** [comment]
> > > With the following changes, I can get the structs to appear on documentation: [thilinarmtb/doxygen-sphinx-breath-cmake@28fc2e1](https://github.com/thilinarmtb/doxygen-sphinx-breath-cmake/commit/28fc2e15e2c61456c1b54267dc42540568b84cc9)
> > > I created a dummy project to test this here: https://github.com/thilinarmtb/doxygen-sphinx-breath-cmake
> > 
> > 
> > I was able to generate docs for struct members by adding the `:members:` tag to the `nomp_types` group in `user-api.rst` file. Currently the issues are,
> > 
> > * `#include <nomp-impl.h>` is present before the description of all the structs in the `nomp-impl.h` file.
> >   image
> > * Only the structs in the `nomp-impl.h` file are being documented.
> 
> Does it go away if we add each struct separately using `doxygenstruct` instead of `doxygengroup`? Also, we need the internal structs to be documented in `internal-api.rst` not in `user-api.rst`.

This works! 

Currently, only the `/include` directory is used as the `DOXYGEN_INPUT_DIR`. I have documented structs in `/backends` as well. Am I supposed to document the structs in the `/include` directory only?

**Comment by thilinarmtb** [comment]
I think we can do both the directories. We will have to change both `DOXYGEN_INPUT_DIR` [here](https://github.com/nomp-org/libnomp/blob/main/docs/Doxyfile.in#L5)
to include the parent directory of both `backend` and `include` and the file extensions [here](https://github.com/nomp-org/libnomp/blob/main/docs/Doxyfile.in#L10) to
include `.c` files.

**Comment by thilinarmtb** [comment]
@NagithaAbeywickrema : I am going to close this PR since most of the internal structs
are now documented as a result of recent PRs which were merged. Please feel free to
issue a new PR if anything is missing there.

**Comment by thilinarmtb** [comment]
@NagithaAbeywickrema : I am going to close this PR since most of the internal structs
are now documented as a result of recent PRs which were merged. Please feel free to
issue a new PR if anything is missing there.

**Pull request closed without merging**
